const CONFIG = {
  map: {
    center: [32.0515, 34.791],
    zoom: 15,
  },

  layers: [
    {
      id: "parcels",
      name: "חלקות",
      file: "data/parcels.geojson",
      type: "geojson",
      style: {
        color: "#9ca3af",
        weight: 0.5,
        fillColor: "#f9fafb",
        fillOpacity: 0.3,
      },
      visible: true,
      interactive: true,
      infoTemplate: "parcel",
      order: 1,
    },
    {
      id: "moshaa",
      name: "מושע",
      file: "data/moshaa.json",
      type: "json",
      builder: "moshaa",
      visible: true,
      interactive: true,
      infoTemplate: "moshaa",
      order: 2,
    },
    {
      id: "municipal",
      name: "בעלות עירונית",
      file: "data/municipal.geojson",
      type: "geojson",
      style: {
        color: "#3b82f6",
        weight: 1.5,
        fillColor: "#3b82f6",
        fillOpacity: 0.15,
        dashArray: "4 4",
      },
      visible: true,
      interactive: true,
      infoTemplate: "municipal",
      order: 3,
    },
    {
      id: "reparcellation-boundaries",
      name: "גבולות רה-פרצלציה",
      file: "data/reparcellation-boundaries.geojson",
      type: "geojson",
      visible: false,
      interactive: false,
      infoTemplate: null,
      order: 3.5,
    },
    {
      id: "reparcellation",
      name: "רה-פרצלציה",
      file: "data/reparcellation.json",
      type: "json",
      builder: "reparcellation",
      visible: false,
      interactive: true,
      infoTemplate: "reparcellation",
      order: 4,
    },
    {
      id: "plans",
      name: "תכניות מקומיות",
      file: "data/plans.json",
      type: "json",
      builder: "plans",
      visible: true,
      interactive: true,
      infoTemplate: "plan",
      order: 5,
    },
    {
      id: "framework-plans",
      name: "תכניות מסגרת",
      file: "data/plans.json",
      type: "json",
      builder: "frameworkPlans",
      visible: false,
      interactive: true,
      infoTemplate: "plan",
      order: 6,
    },
    {
      id: "gush-boundaries",
      name: "גושים",
      file: "data/gush-boundaries.geojson",
      type: "geojson",
      style: {
        color: "#d1d5db",
        weight: 1.5,
        fillOpacity: 0,
        dashArray: "6 4",
      },
      visible: true,
      interactive: false,
      infoTemplate: null,
      order: 7,
    },
    {
      id: "sites",
      name: "אתרים",
      file: "data/sites.json",
      type: "json",
      builder: "sites",
      visible: true,
      interactive: true,
      infoTemplate: "site",
      order: 8,
    },
  ],

  tabs: [
    { id: "info", label: "מידע" },
    { id: "reparcellation", label: "רה-פרצלציה" },
    { id: "plans", label: "תכניות" },
    { id: "stats", label: "סטטיסטיקות" },
  ],

  siteColors: {
    1: "#E8635A",
    2: "#5B8DEF",
    3: "#3BB076",
    4: "#9B72CF",
    5: "#E09B4F",
  },

  siteNames: {
    "hatikva-hanoch-tarfon": { num: 1, name: "התקווה-חנוך-טרפון" },
    "hatishbi-sasson": { num: 2, name: "תשבי-ששון" },
    "derech-hahagana": { num: 3, name: "דרך ההגנה" },
    "haverod-park": { num: 4, name: "הורד-פארק" },
    "haverod-yechiam-leblov": { num: 5, name: "הורד-יחיעם-לבלוב" },
  },

  reparcellationStatuses: {
    מאושרת: {
      color: "#166534",
      bg: "#f0fdf4",
      label: "מאושרת",
      order: 1,
    },
    מופקדת: {
      color: "#92400e",
      bg: "#fffbeb",
      label: "מופקדת",
      order: 2,
    },
    מאושר_להפקדה: {
      color: "#1e40af",
      bg: "#eff6ff",
      label: "מאושר להפקדה",
      order: 3,
    },
    לקראת_דיון_בהפקדה: {
      color: "#9333ea",
      bg: "#faf5ff",
      label: "לקראת דיון בהפקדה",
      order: 4,
    },
    תחילת_תכנון: {
      color: "#6b7280",
      bg: "#f3f4f6",
      label: "תחילת תכנון",
      order: 5,
    },
    לא_טופל: {
      color: "#991b1b",
      bg: "#fef2f2",
      label: "לא טופל",
      order: 6,
    },
  },

  planColors: [
    "#7c3aed",
    "#2563eb",
    "#0891b2",
    "#059669",
    "#6d28d9",
    "#1d4ed8",
    "#0e7490",
    "#047857",
    "#8b5cf6",
    "#3b82f6",
    "#06b6d4",
    "#10b981",
    "#a78bfa",
    "#60a5fa",
    "#22d3ee",
    "#34d399",
    "#4f46e5",
    "#0284c7",
  ],

  frameworkGushThreshold: 4,
};
